### ISSUE TITLE
Search engine semantic wierdness not returning relevant results.

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-nlp#11]
I've noticed something weird in the search. When I search using just a term it doesnt show the answers that contain that term...

E.g. Searching just 'prosaic' does not show - 'What does prosaic alignment mean?' , until I include 'what', i.e. I have to search 'what prosaic' to get the answer to show up as a result. Similiar results for other terms - e.g. 'corrigible' does not return 'what is corrigibility', until I search 'what corrigible'.

Depending on how you assume people use the search bar this might be a problem. I would ususally just type in only the core term, not see a result and assume that the site does not have an answer to that question yet. Its only because I know for a fact that the answers above were for sure approved that I even bothered trying different semantics. You could lose some readers this way.

I posted this in the dev channel but here is also an issue for it. I don't know which one of the repos was for search. I am just assuming NLP was the right one.

**Comment by ccstan99** [comment]
Thanks for writing this up! I'm closing this here and moving this over to https://github.com/StampyAI/stampy-ui/issues/194. Feel free to add additional comments there if relevant.
